import Head from "next/head";
import Image from "next/image";
import Actions from "../components/Actions";
import Header from "../components/Header";
import Timer from "../components/Timer";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pomodoro Timer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Timer />
      <Actions />
    </div>
  );
}
